version: '3'

services:
  app:
    working_dir: /app
    container_name: app
    volumes:
      - .:/app
    build: .
    depends_on:
      - redis
      - memcached
  redis:
    container_name: Redis
    image: "redis:latest"
    command: redis-server

  memcached:
    container_name: memcached
    image: memcached:latest